[app]
name = "TODO"
timezone = "Asia/Shanghai"

[app.log]
level = "info"

[web]
port = 20808
debug = true

[web.acl]
enabled = false
tokenFrom = "header" # header, query
whitelist = [
    "/api/user/login",
    "/api/user/register"
]

[db]
#type = "postgres"
#dsn = ""
type = "sqlite"
dsn = "db.db"

[redis]
host = "localhost"
port = 6379
password = ""
keyPrefix = ""

[mqtt]
