[app]
name = "TODO"
timezone = "Asia/Shanghai"

[app.log]
level = "info"

[web]
listenAddress = ":20808"
debug = true

[web.auth]
enabled = true
whitelist = [
    "/favicon.ico",
    "/api/v1/litelink/todo/frameworks/versions",
]
sessionIdKey = "kt-session-id"
sessionExpireInHours = 24


[db]
#type = "postgres"
#dsn = ""
type = "sqlite"
dsn = "db.db"

[redis]
host = "localhost"
port = 6379
password = ""
keyPrefix = ""

[mqtt]
